gateway:
    container_name: gateway_container
    build:
      context: ../ApiGateWay
      dockerfile: Dockerfile
    restart: always
    ports:
      - 4000:4000
    env_file: ../ApiGateWay/.env
    environment:
        - ENABLE_APM=1
        - GATEWAY_JWT_TOKEN=b6f0bae41922440a99c1bc13a1a120cd
        - JWT_TOKEN=8db8f85991bb28f45ac0107f2a1b349c
        - NODE_ENV=development
        - SECRET_KEY_ONE=032c5c3cfc37938ae6dd43d3a3ec7834
        - SECRET_KEY_TWO=d66e377018c0bc0b5772bbc9b131e6d9
        - AUTH_BASE_URL=http://auth_container:4002
        - USERS_BASE_URL=http://localhost:4003
        - GIG_BASE_URL=http://localhost:4004
        - MESSAGE_BASE_URL=http://localhost:4005
        - ORDER_BASE_URL=http://localhost:4006
        - REVIEW_BASE_URL=http://localhost:4007
        - REDIS_HOST=redis://redis_container:6379
