version: '3.9'
services:

  mongodb:
      container_name: mongodb_container
      image: mongo:latest
      restart: always
      ports:
        - 27017:27017
      volumes:
        - ./docker-volumes/data:/data/db
  messagebroker:
    image: rabbitmq:management
    container_name: messagebroker
    hostname: course-mq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
  auth:
    container_name: auth_container
    build:
      context: ../AuthService
      dockerfile: Dockerfile
    restart: always
    ports:
      - 4000:4000
    env_file: ../AuthService/.env
    environment:
      - MONGODB_URL=mongodb://mongodb_container:27017/auth
      - JWT_SECRET_KEY="6f1b869691544d8a8c73a79006fc71e8"
      - PORT=4000
      



  course:
    container_name: course_container
    build:
      context: ../Course.API
      dockerfile: Dockerfile
    restart: always
    ports:
      - 4001:4001
    env_file: ../Course.API/.env
    environment:
      - MONGODB_URL=mongodb://mongodb_container:27017/course
      - JWT_SECRET_KEY="6f1b869691544d8a8c73a79006fc71e8"
      - RABBITMQ_URL=amqp://course-mq:5672
      - PORT=4001
  cart:
    container_name: cart_container
    build:
      context: ../Cart.API
      dockerfile: Dockerfile
    restart: always
    ports:
      - 4002:4002
    env_file: ../Cart.API/.env
    environment:
      - MONGODB_URL=mongodb://mongodb_container:27017/cart
      - JWT_SECRET_KEY="6f1b869691544d8a8c73a79006fc71e8"
      - RABBITMQ_URL=amqp://course-mq:5672
      - PORT=4002
  
  order:
    container_name: order_container
    build:
      context: ../Order.API
      dockerfile: Dockerfile
    restart: always
    ports:
      - 4003:4003
    env_file: ../Order.API/.env
    environment:
      - MONGODB_URL=mongodb://mongodb_container:27017/order
      - JWT_SECRET_KEY="6f1b869691544d8a8c73a79006fc71e8"
      - RABBITMQ_URL=amqp://course-mq:5672
      - PORT=4003


  review:
    container_name: review_container
    build:
      context: ../ReviewService
      dockerfile: Dockerfile
    restart: always
    ports:
      - 4004:4004
    env_file: ../ReviewService/.env
    environment:
      - MONGODB_URL=mongodb://mongodb_container:27017/order
      - JWT_SECRET_KEY="6f1b869691544d8a8c73a79006fc71e8"
      - RABBITMQ_URL=amqp://course-mq:5672
      - PORT=4004
